{% set python_min = '3.10' %}
{% set name = "xmacis2py" %}
{% set version = "1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/xmacis2py-{{ version }}.tar.gz
  sha256: 476d428e9c1b6592fa6ab24993428582fb4aea870418529c22f82a9db1e17d3b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64
    - pip
  run:
    - python >={{ python_min }}
    - matplotlib-base >=3.7
    - metpy >=1.5.1
    - numpy >=1.24
    - pandas >=2.2

test:
  imports:
    - xmacis2py
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/edrewitz/xmACIS2Py
  summary: ACIS2 Data Analysis and Graphical Generation
  license: MIT
  license_file: LICENSE
  doc_url: https://github.com/edrewitz/xmACIS2Py/blob/main/README.md


extra:
  recipe-maintainers:
    - edrewitz
